Removed IrisTK Eclipse project from dependencies; Still unable to build outside of Eclipse due to NoClassDefFoundError in relation to subclass(es) of Event